# NUMPY

In [1]:
import numpy as np

In [2]:
oneD = np.array([0,1,2,3])

In [3]:
oneD = np.array(range(5))

In [4]:
oneD

array([0, 1, 2, 3, 4])

In [5]:
twoD = np.array([range(0,5),range(15,20)])

In [6]:
twoD

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [7]:
twoD.ndim

2

In [8]:
twoD[:2]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [9]:
one = np.arange(20).reshape(5,-1)
two = np.arange(40,60).reshape(5,-1)

In [10]:
one

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
two

array([[40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [12]:
np.hstack([one,two])

array([[ 0,  1,  2,  3, 40, 41, 42, 43],
       [ 4,  5,  6,  7, 44, 45, 46, 47],
       [ 8,  9, 10, 11, 48, 49, 50, 51],
       [12, 13, 14, 15, 52, 53, 54, 55],
       [16, 17, 18, 19, 56, 57, 58, 59]])

In [13]:
np.vstack([one,two])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [14]:
one ** 10

array([[          0,           1,        1024,       59049],
       [    1048576,     9765625,    60466176,   282475249],
       [ 1073741824,  -808182895,  1410065408,   167620825],
       [ 1787822080,   419538377,  1491846144,  1124772961],
       [          0,  1654238625,  1349403648, -2147040887]], dtype=int32)

In [15]:
one + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [16]:
one + two

array([[40, 42, 44, 46],
       [48, 50, 52, 54],
       [56, 58, 60, 62],
       [64, 66, 68, 70],
       [72, 74, 76, 78]])

In [17]:
one * two

array([[   0,   41,   84,  129],
       [ 176,  225,  276,  329],
       [ 384,  441,  500,  561],
       [ 624,  689,  756,  825],
       [ 896,  969, 1044, 1121]])

In [18]:
one

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
one + np.array(range(4))

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [20]:
np.sin(one)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [21]:
np.cos(one)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462]])

In [22]:
np.max(one)

19

In [23]:
np.min(one , axis=1)

array([ 0,  4,  8, 12, 16])

In [24]:
np.mean(one)

9.5

In [25]:
np.mean(one, axis=0)

array([ 8.,  9., 10., 11.])

In [26]:
np.std(one,axis=0)

array([5.65685425, 5.65685425, 5.65685425, 5.65685425])

In [27]:
data=np.linspace(0, 2*np.pi, 10)

In [28]:
data

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

## Some More Numpy Functions - Statistics

- min, max
- mean
- median
- average
- variance
- standard devidation

In [29]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [30]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [31]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))

# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function
dev= np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


## Numpy Random Module

- rand : Random values in a given shape.
- randn : Return a sample (or samples) from the “standard normal” distribution.
- randint : Return random integers from low (inclusive) to high (exclusive).
- random : Return random floats in the half-open interval [0.0, 1.0)
- choice : Generates a random sample from a given 1-D array
- Shuffle : Shuffles the contents of a sequence

In [32]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [33]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [34]:
#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
